# Generated by Django 5.2.17 on 2026-09-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_article_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='news_api.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
