# Generated by Django 5.2.17 on 2026-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_smtpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='reply_to',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='security_protocol',
            field=models.CharField(choices=[('TLS', 'TLS'), ('SSL', 'SSL'), ('NONE', 'None')], default='TLS', max_length=10),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
