# Generated by Django 6.1.1 on 2026-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='daily_send_time',
            field=models.CharField(default='08:00', max_length=5),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='emails_received',
            field=models.IntegerField(default=0),
        ),
    ]
