# Generated by Django 6.1.1 on 2026-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0009_admin2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
