# Generated by Django 6.1.1 on 2026-09-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0010_subscriber_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
