# Generated by Django 6.1.1 on 2026-09-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0011_rssfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, default='', max_length=500)),
                ('youtube', models.URLField(blank=True, default='', max_length=500)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('insta', models.URLField(blank=True, default='', max_length=500)),
                ('facebook', models.URLField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
