# Generated by Django 6.1.1 on 2026-09-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0013_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
