# Generated by Django 6.1.1 on 2026-09-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0014_remove_blogpost_image_blogpost_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
