# Generated by Django 6.1.1 on 2026-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0016_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaconfig',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmediaconfig',
            name='email',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmediaconfig',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmediaconfig',
            name='insta',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmediaconfig',
            name='twitter',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmediaconfig',
            name='youtube',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
