DEFAULT_RSS_FEEDS = [
{"name":"CrowdStrike","url":"https://www.crowdstrike.com/blog/feed/","category":"Cybersecurity"},
{"name":"Cisco Talos","url":"https://blog.talosintelligence.com/rss/","category":"Cybersecurity"},
{"name":"Malwarebytes Labs","url":"https://www.malwarebytes.com/blog/feed/index.xml","category":"Cybersecurity"},
{"name":"ESET WeLiveSecurity","url":"https://www.welivesecurity.com/en/rss/feed/","category":"Cybersecurity"},
{"name":"Sophos Threat Research","url":"https://news.sophos.com/en-us/category/threat-research/feed/","category":"Cybersecurity"},
{"name":"Trend Micro Research","url":"https://feeds.feedburner.com/TrendMicroSimplySecurity","category":"Cybersecurity"},
{"name":"Rapid7","url":"https://www.rapid7.com/blog/rss/","category":"Cybersecurity"},
{"name":"Tenable","url":"https://www.tenable.com/blog/feed","category":"Cybersecurity"},
{"name":"Zero Day Initiative","url":"https://www.zerodayinitiative.com/rss/published/","category":"Cybersecurity"},
{"name":"Zero Day Initiative Blog","url":"https://www.zerodayinitiative.com/blog?format=rss","category":"Cybersecurity"},
{"name":"CyberArk","url":"https://www.cyberark.com/feed/","category":"Cybersecurity"},
{"name":"GitLab Security Releases","url":"https://about.gitlab.com/security-releases.xml","category":"Cybersecurity"},
{"name":"Proofpoint","url":"https://www.proofpoint.com/us/rss.xml","category":"Cybersecurity"},
{"name":"Ars Technica Security","url":"https://arstechnica.com/security/feed/","category":"Cybersecurity"},
{"name":"PortSwigger Research","url":"https://portswigger.net/research/rss","category":"Cybersecurity"},
{"name":"PortSwigger Blog","url":"https://portswigger.net/blog/rss","category":"Cybersecurity"},
{"name":"Eclypsium","url":"https://eclypsium.com/feed/","category":"Cybersecurity"},
{"name":"Wordfence","url":"https://www.wordfence.com/blog/feed/atom","category":"Cybersecurity"},
{"name":"Snyk","url":"https://snyk.io/blog/feed","category":"Cybersecurity"},
{"name":"Veracode","url":"https://www.veracode.com/blog/feed","category":"Cybersecurity"},
{"name":"SonarSource","url":"https://www.sonarsource.com/blog/rss.xml","category":"Cybersecurity"},
{"name":"Censys","url":"https://censys.com/feed","category":"Cybersecurity"},
{"name":"Cisco Security Blog","url":"https://blogs.cisco.com/security/feed","category":"Cybersecurity"},
{"name":"Cisco Security Newsroom","url":"https://newsroom.cisco.com/c/services/i/servlets/newsroom/rssfeed.json?feed=security","category":"Cybersecurity"},
{"name":"Google Security Blog","url":"https://security.googleblog.com/feeds/posts/default","category":"Cybersecurity"},
{"name":"Google Threat Analysis Group","url":"https://blog.google/threat-analysis-group/rss","category":"Cybersecurity"},
{"name":"Mandiant Threat Intelligence","url":"https://cloudblog.withgoogle.com/topics/threat-intelligence/rss/","category":"Cybersecurity"},
{"name":"Google Online Security","url":"https://googleonlinesecurity.blogspot.com/atom.xml","category":"Cybersecurity"},
{"name":"Google Safety & Security","url":"https://blog.google/technology/safety-security/rss","category":"Cybersecurity"},
{"name":"Fastly Security","url":"https://www.fastly.com/blog_rss.xml","category":"Cybersecurity"},
{"name":"AlienVault","url":"https://levelblue.com/site/blog-all-rss/rss","category":"Cybersecurity"},
{"name":"LevelBlue Security","url":"https://levelblue.com/site/blog-all-rss/rss","category":"Cybersecurity"},
{"name":"Securelist","url":"https://securelist.com/feed/","category":"Cybersecurity"},
{"name":"SANS Internet Storm Center","url":"https://isc.sans.edu/rssfeed_full.xml","category":"Cybersecurity"},
{"name":"SANS NewsBites","url":"https://isc.sans.edu/rssfeed_full.xml","category":"Cybersecurity"},
{"name":"HackerOne","url":"https://www.hackerone.com/blog.rss","category":"Cybersecurity"},
{"name":"Graham Cluley","url":"https://www.grahamcluley.com/feed/","category":"Cybersecurity"},
{"name":"IT Security Guru","url":"https://www.itsecurityguru.org/feed/","category":"Cybersecurity"},
{"name":"GBHackers","url":"https://gbhackers.com/feed","category":"Cybersecurity"},
{"name":"Latest Hacking News","url":"https://latesthackingnews.com/feed/","category":"Cybersecurity"},
{"name":"KitPloit","url":"https://www.kitploit.com/feeds/posts/default","category":"Cybersecurity"},
{"name":"Koddos Security","url":"https://blog.koddos.net/feed/","category":"Cybersecurity"},
{"name":"VirusTotal","url":"https://blog.virustotal.com/feeds/posts/default","category":"Cybersecurity"},
{"name":"Red Canary","url":"https://www.redcanary.com/feed/","category":"Cybersecurity"},
{"name":"Lab52","url":"https://lab52.io/blog/feed/","category":"Cybersecurity"},
{"name":"Praetorian","url":"https://www.praetorian.com/blog/feed","category":"Cybersecurity"},
{"name":"1Password Security","url":"https://blog.1password.com/index.xml","category":"Cybersecurity"},
{"name":"Broadcom Symantec","url":"https://sed-cms.broadcom.com/rss/v1/blogs/rss.xml","category":"Cybersecurity"},
{"name":"Chromium Security","url":"https://blog.chromium.org/feeds/posts/default","category":"Cybersecurity"},
{"name":"PCI Security Standards Council","url":"https://blog.pcisecuritystandards.org/rss.xml","category":"Cybersecurity"},
{"name":"NCSC Netherlands","url":"https://advisories.ncsc.nl/rss/advisories","category":"Cybersecurity"},
{"name":"ACSC Australia Advisories","url":"https://www.cyber.gov.au/rss/advisories","category":"Cybersecurity"},
{"name":"ACSC Australia Alerts","url":"https://www.cyber.gov.au/rss/alerts","category":"Cybersecurity"},
{"name":"ACSC Australia Threats","url":"https://www.cyber.gov.au/rss/threats","category":"Cybersecurity"},
{"name":"CISA ICS Advisories","url":"https://www.cisa.gov/cybersecurity-advisories/ics-advisories.xml","category":"Cybersecurity"},
{"name":"SANS Security Advisories","url":"https://www.sans.org/rss/","category":"Cybersecurity"},
{"name":"Siemens ProductCERT","url":"https://cert-portal.siemens.com/productcert/rss/advisories.atom","category":"Cybersecurity"},
{"name":"Ubuntu Security Notices","url":"https://ubuntu.com/security/notices/rss.xml","category":"Cybersecurity"},
{"name":"AWS Security Bulletins","url":"https://aws.amazon.com/security/security-bulletins/feed/","category":"Cybersecurity"},
{"name":"Trend Micro Research","url":"https://feeds.trendmicro.com/TrendMicroResearch","category":"Cybersecurity"},
{"name":"Sophos Naked Security","url":"https://nakedsecurity.sophos.com/feed/","category":"Cybersecurity"},
{"name":"Palo Alto Unit 42","url":"https://unit42.paloaltonetworks.com/feed/","category":"Cybersecurity"},
{"name":"Palo Alto Security Blog","url":"https://www.paloaltonetworks.com/blog/feed/","category":"Cybersecurity"},
{"name":"Fortinet FortiGuard Labs","url":"https://feeds.fortinet.com/fortinet/blog/threatresearch","category":"Cybersecurity"},
{"name":"F-Secure Labs","url":"https://blog.f-secure.com/feed/","category":"Cybersecurity"},
{"name":"Avast Threat Labs","url":"https://decoded.avast.io/feed/","category":"Cybersecurity"},
{"name":"Emsisoft Blog","url":"https://www.emsisoft.com/en/blog/feed/","category":"Cybersecurity"},
{"name":"Dr.Web Virus Alerts","url":"https://news.drweb.com/rss/get/?c=23","category":"Cybersecurity"},
{"name":"Quick Heal Security Labs","url":"https://blogs.quickheal.com/feed/","category":"Cybersecurity"},
{"name":"K7 Computing","url":"https://blog.k7computing.com/feed/","category":"Cybersecurity"},
{"name":"Data Security Council of India","url":"https://www.dsci.in/rss.xml","category":"Cybersecurity"},
{"name":"Seqrite","url":"https://www.seqrite.com/blog/feed/","category":"Cybersecurity"},
{"name":"CyRAACS","url":"https://cyraacs.com/feed/","category":"Cybersecurity"},
{"name":"Cyber Defense Magazine","url":"https://www.cyberdefensemagazine.com/feed/","category":"Cybersecurity"},
]
